data:
  raw_path: src/data/raw/Symptom2Disease.csv
  target_column: label
  text_column: text
  drop_columns:
    - "Unnamed: 0"
  test_size: 0.2
  random_state: 42

features:
  tfidf_ngram_range: [1, 2]
  tfidf_max_features: 20000

model:
  type: logistic_regression   # logistic_regression | random_forest | linear_svc | naive_bayes
  # Logistic Regression
  logistic_c: 1.0
  logistic_max_iter: 1000
  logistic_solver: lbfgs
  random_state: 42
  # Random Forest
  rf_n_estimators: 100
  rf_max_depth: null
  # Linear SVC
  svm_c: 1.0
  svm_max_iter: 2000
  # Naive Bayes (MultinomialNB)
  nb_alpha: 1.0

training:
  experiment_name: devlocare-training
  run_name: lr_tfidf_unibi_baseline
  model_output_path: models/model.pkl

mlflow:
  tracking_uri: dagshub  # local or dagshub
  dagshub_repo_owner: "uzairazmat"
  dagshub_repo_name: "DevloCare_ML_Pipeline"

